# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2016, 2020 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

# Default values for hybrid-cluster-manager-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

arch:
  - amd64
  - ppc64le
  - s390x
replicas: 1
pullSecret: null
nodeSelector:
  enabled: false
  os: ""
  customLabelSelector: ""
  customLabelValue: ""
imageTagPostfix: ""
cfcRouterUrl: null

compliance:
  repository: quay.io/open-cluster-management/mcm-compliance
  tag: 3.6.0
  pullPolicy: Always
  resources:
    requests:
      memory: "64Mi"
      cpu: "25m"
    limits:
      memory: "512Mi"
      cpu: "100m"
grcui:
  image:
    repository: quay.io/open-cluster-management/grc-ui
    tag: 3.6.0
    pullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"
grcuiapi:
  image:
    repository: quay.io/open-cluster-management/grc-ui-api
    tag: 3.6.0
    pullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "500m"