# Copyright (c) 2020 Red Hat, Inc.
global:
  imageOverrides:
    governance_policy_propagator: ""
    grc_ui: ""
    grc_ui_api: ""
  pullPolicy: Always
  

arch:
  - amd64
  - ppc64le
  - s390x
replicas: 1
pullSecret: null
nodeSelector:
  enabled: false
  os: ""
  customLabelSelector: ""
  customLabelValue: ""

compliance:
  resources:
    requests:
      memory: "64Mi"
      cpu: "25m"
grcui:
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
grcuiapi:
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
