# Copyright (c) 2020 Red Hat, Inc.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grcuiapi
  labels:
    app: {{ template "grc.name" . }}
    component: "ocm-grcuiapi"
    chart: {{ template "grc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "grc.name" . }}
    helm.sh/chart: {{ template "grc.chart" . }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Release.Name }}-grc-secrets
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: {{ template "grc.name" . }}
    component: "ocm-grcuiapi"
    release: {{ .Release.Name }}
