# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "grc.fullname" . }}-ca-cert
  labels:
    app: {{ template "grc.name" . }}
    chart: {{ template "grc.chart" . }}
    release: {{ .Release.Name }}
    component: "mcm-grcuiapi"
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "grc.name" . }}
    helm.sh/chart: {{ template "grc.chart" . }}
spec:
  secretName: {{ .Release.Name }}-grc-secrets
  issuerRef:
    name: {{ .Release.Name }}-mcm-server-ca-issuer
    kind: Issuer
  commonName: {{ template "grc.fullname" . }}
  isCA: true
  organization:
  - IBM
