# Copyright (c) 2020 Red Hat, Inc.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.open-cluster-management.io/auth-type: access-token
    kubernetes.io/ingress.class: ingress-open-cluster-management
  name: {{ .Release.Name }}-grcui
  labels:
    app: {{ template "grc.name" . }}
    chart: {{ template "grc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "grc.name" . }}
    helm.sh/chart: {{ template "grc.chart" . }}
spec:
  rules:
  - http:
      paths:
      - path: /multicloud/policies
        backend:
          serviceName: {{ .Release.Name }}-grcui
          servicePort: 3000
